### ISSUE TITLE
Update the Flipper Time Tracker app for the SDK version 0.104 f7

### ISSUE THREAD

**Issue by furippa** [MassivDash/flipper-tracker#1]
Hello!

Your Flipper Time Tracker app version `0.1` fails to build with the SDK version `0.104.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/66f8eb70123f464e9bc80f80/page)
[View build actions](https://github.com/flipperdevices/flipper-application-catalog/actions/runs/11090169327)

Flipper Team

**Comment by MassivDash** [comment]
@furippa any specific reason why number-input gui module was removed in the 104 version ?  I do not see any depreciation warning ... the branch https://github.com/flipperdevices/flipperzero-firmware/tree/0.104.0-rc/applications/services/gui/modules clearly does not have the number-input module, which is the build error from your issue about my app
